title: Hari Stoyanov
description: Welcome to my professional site.
theme: minima
plugins:
  - jekyll-feed

navbar:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Personal
    url: /personal/
